/**:
  ros__parameters:
    min_longitudinal_offset: 2.2
    max_longitudinal_offset: 2.4
    min_lateral_offset: -1.4
    max_lateral_offset: 1.4
    min_height_offset: 1.1
    max_height_offset: 1.3
